using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BemkoStanyMagazynowe.AAA
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     Ten kod został wygenerowany przez narzędzie.
    //     Wersja wykonawcza:2.0.50727.5485
    //
    //     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
    //     kod zostanie ponownie wygenerowany.
    // </auto-generated>
    //------------------------------------------------------------------------------



    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "https://megacennik.eu/pobierzStanMagazynowyProducenta/", ConfigurationName = "pobierzStanMagazynowyProducenta")]
    public interface pobierzStanMagazynowyProducenta
    {

        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ operacja „pobierzStanMagazynowyProducenta” nie jest ani wywołaniem RPC, ani opakowanym dokumentem.
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.example.org/pobierzStanMagazynowyProducenta/NewOperation", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        odpowiedz pobierzStanMagazynowyProducenta(pytanie request);
    }

    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://megacennik.eu/pobierzStanMagazynowyProducenta/")]
    public partial class pytanieTyp
    {

        private dokumentTyp dokumentField;

        private kontoTyp kontoField;

        private towarPytanieTyp[] towaryField;

        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public dokumentTyp dokument
        {
            get
            {
                return this.dokumentField;
            }
            set
            {
                this.dokumentField = value;
            }
        }

        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public kontoTyp konto
        {
            get
            {
                return this.kontoField;
            }
            set
            {
                this.kontoField = value;
            }
        }

        /// <uwagi/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("towar", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public towarPytanieTyp[] towary
        {
            get
            {
                return this.towaryField;
            }
            set
            {
                this.towaryField = value;
            }
        }
    }

    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://megacennik.eu/pobierzStanMagazynowyProducenta/")]
    public partial class dokumentTyp
    {

        private string wersjaField;

        private System.DateTime znacznikField;

        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string wersja
        {
            get
            {
                return this.wersjaField;
            }
            set
            {
                this.wersjaField = value;
            }
        }

        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public System.DateTime znacznik
        {
            get
            {
                return this.znacznikField;
            }
            set
            {
                this.znacznikField = value;
            }
        }
    }

    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://megacennik.eu/pobierzStanMagazynowyProducenta/")]
    public partial class towarOdpowiedzTyp
    {

        private string symbolField;

        private double iloscField;

        private bool iloscFieldSpecified;

        private System.DateTime dataField;

        private bool dataFieldSpecified;

        /// <uwagi/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string symbol
        {
            get
            {
                return this.symbolField;
            }
            set
            {
                this.symbolField = value;
            }
        }

        /// <uwagi/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double ilosc
        {
            get
            {
                return this.iloscField;
            }
            set
            {
                this.iloscField = value;
            }
        }

        /// <uwagi/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool iloscSpecified
        {
            get
            {
                return this.iloscFieldSpecified;
            }
            set
            {
                this.iloscFieldSpecified = value;
            }
        }

        /// <uwagi/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }

        /// <uwagi/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataSpecified
        {
            get
            {
                return this.dataFieldSpecified;
            }
            set
            {
                this.dataFieldSpecified = value;
            }
        }
    }

    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://megacennik.eu/pobierzStanMagazynowyProducenta/")]
    public partial class odpowiedzTyp
    {

        private towarOdpowiedzTyp[] towaryField;

        private string wersjaField;

        private System.DateTime znacznikField;

        private bool znacznikFieldSpecified;

        /// <uwagi/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("towar", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public towarOdpowiedzTyp[] towary
        {
            get
            {
                return this.towaryField;
            }
            set
            {
                this.towaryField = value;
            }
        }

        /// <uwagi/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string wersja
        {
            get
            {
                return this.wersjaField;
            }
            set
            {
                this.wersjaField = value;
            }
        }

        /// <uwagi/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime znacznik
        {
            get
            {
                return this.znacznikField;
            }
            set
            {
                this.znacznikField = value;
            }
        }

        /// <uwagi/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool znacznikSpecified
        {
            get
            {
                return this.znacznikFieldSpecified;
            }
            set
            {
                this.znacznikFieldSpecified = value;
            }
        }
    }

    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://megacennik.eu/pobierzStanMagazynowyProducenta/")]
    public partial class towarPytanieTyp
    {

        private string symbolField;

        private double iloscField;

        private bool iloscFieldSpecified;

        /// <uwagi/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string symbol
        {
            get
            {
                return this.symbolField;
            }
            set
            {
                this.symbolField = value;
            }
        }

        /// <uwagi/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double ilosc
        {
            get
            {
                return this.iloscField;
            }
            set
            {
                this.iloscField = value;
            }
        }

        /// <uwagi/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool iloscSpecified
        {
            get
            {
                return this.iloscFieldSpecified;
            }
            set
            {
                this.iloscFieldSpecified = value;
            }
        }
    }

    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://megacennik.eu/pobierzStanMagazynowyProducenta/")]
    public partial class kontoTyp
    {

        private string loginField;

        private string hasloField;

        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string login
        {
            get
            {
                return this.loginField;
            }
            set
            {
                this.loginField = value;
            }
        }

        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string haslo
        {
            get
            {
                return this.hasloField;
            }
            set
            {
                this.hasloField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class pytanie
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "pytanie", Namespace = "https://megacennik.eu/pobierzStanMagazynowyProducenta/", Order = 0)]
        public pytanieTyp pytanie1;

        public pytanie()
        {
        }

        public pytanie(pytanieTyp pytanie1)
        {
            this.pytanie1 = pytanie1;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class odpowiedz
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "odpowiedz", Namespace = "https://megacennik.eu/pobierzStanMagazynowyProducenta/", Order = 0)]
        public odpowiedzTyp odpowiedz1;

        public odpowiedz()
        {
        }

        public odpowiedz(odpowiedzTyp odpowiedz1)
        {
            this.odpowiedz1 = odpowiedz1;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface pobierzStanMagazynowyProducentaChannel : pobierzStanMagazynowyProducenta, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class pobierzStanMagazynowyProducentaClient : System.ServiceModel.ClientBase<pobierzStanMagazynowyProducenta>, pobierzStanMagazynowyProducenta
    {

        public pobierzStanMagazynowyProducentaClient()
        {
        }

        public pobierzStanMagazynowyProducentaClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public pobierzStanMagazynowyProducentaClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public pobierzStanMagazynowyProducentaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public pobierzStanMagazynowyProducentaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        odpowiedz pobierzStanMagazynowyProducenta.pobierzStanMagazynowyProducenta(pytanie request)
        {
            return base.Channel.pobierzStanMagazynowyProducenta(request);
        }

        public odpowiedzTyp pobierzStanMagazynowyProducenta(pytanieTyp pytanie1)
        {
            pytanie inValue = new pytanie();
            inValue.pytanie1 = pytanie1;
            odpowiedz retVal = ((pobierzStanMagazynowyProducenta)(this)).pobierzStanMagazynowyProducenta(inValue);
            return retVal.odpowiedz1;
        }
    }

}