//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebServiceTest.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback b2b_towaryOperationCompleted;
        
        private System.Threading.SendOrPostCallback b2b_grupyOperationCompleted;
        
        private System.Threading.SendOrPostCallback b2b_CenySpecjalneOperationCompleted;
        
        private System.Threading.SendOrPostCallback b2b_kontrahenciOperationCompleted;
        
        private System.Threading.SendOrPostCallback b2b_danebinarneOperationCompleted;
        
        private System.Threading.SendOrPostCallback b2b_operatorzyOperationCompleted;
        
        private System.Threading.SendOrPostCallback b2b_dystrybutorzyOperationCompleted;
        
        private System.Threading.SendOrPostCallback b2b_cenyklientowOperationCompleted;
        
        private System.Threading.SendOrPostCallback b2b_cechyOperationCompleted;
        
        private System.Threading.SendOrPostCallback b2b_stanyOperationCompleted;
        
        private System.Threading.SendOrPostCallback b2b_zamnagOperationCompleted;
        
        private System.Threading.SendOrPostCallback b2b_zamelemOperationCompleted;
        
        private System.Threading.SendOrPostCallback b2b_nowyAdresOperationCompleted;
        
        private System.Threading.SendOrPostCallback b2b_traelemOperationCompleted;
        
        private System.Threading.SendOrPostCallback b2b_tranagOperationCompleted;
        
        private System.Threading.SendOrPostCallback b2b_cenyOperationCompleted;
        
        private System.Threading.SendOrPostCallback b2b_twrzamiennikiOperationCompleted;
        
        private System.Threading.SendOrPostCallback testOperationCompleted;
        
        private System.Threading.SendOrPostCallback b2b_verifyUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback b2b_setNewUserPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback b2b_NumerWebOperationCompleted;
        
        private System.Threading.SendOrPostCallback b2b_cdloginlogoutOperationCompleted;
        
        private System.Threading.SendOrPostCallback b2b_nowyDokumentZamOperationCompleted;
        
        private System.Threading.SendOrPostCallback b2b_nowyDokumentZamHanOperationCompleted;
        
        private System.Threading.SendOrPostCallback b2b_adresykontrahentowOperationCompleted;
        
        private System.Threading.SendOrPostCallback b2b_AdresyKontrahentaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::WebServiceTest.Properties.Settings.Default.WebServiceTest_WebReference_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event b2b_towaryCompletedEventHandler b2b_towaryCompleted;
        
        /// <remarks/>
        public event b2b_grupyCompletedEventHandler b2b_grupyCompleted;
        
        /// <remarks/>
        public event b2b_CenySpecjalneCompletedEventHandler b2b_CenySpecjalneCompleted;
        
        /// <remarks/>
        public event b2b_kontrahenciCompletedEventHandler b2b_kontrahenciCompleted;
        
        /// <remarks/>
        public event b2b_danebinarneCompletedEventHandler b2b_danebinarneCompleted;
        
        /// <remarks/>
        public event b2b_operatorzyCompletedEventHandler b2b_operatorzyCompleted;
        
        /// <remarks/>
        public event b2b_dystrybutorzyCompletedEventHandler b2b_dystrybutorzyCompleted;
        
        /// <remarks/>
        public event b2b_cenyklientowCompletedEventHandler b2b_cenyklientowCompleted;
        
        /// <remarks/>
        public event b2b_cechyCompletedEventHandler b2b_cechyCompleted;
        
        /// <remarks/>
        public event b2b_stanyCompletedEventHandler b2b_stanyCompleted;
        
        /// <remarks/>
        public event b2b_zamnagCompletedEventHandler b2b_zamnagCompleted;
        
        /// <remarks/>
        public event b2b_zamelemCompletedEventHandler b2b_zamelemCompleted;
        
        /// <remarks/>
        public event b2b_nowyAdresCompletedEventHandler b2b_nowyAdresCompleted;
        
        /// <remarks/>
        public event b2b_traelemCompletedEventHandler b2b_traelemCompleted;
        
        /// <remarks/>
        public event b2b_tranagCompletedEventHandler b2b_tranagCompleted;
        
        /// <remarks/>
        public event b2b_cenyCompletedEventHandler b2b_cenyCompleted;
        
        /// <remarks/>
        public event b2b_twrzamiennikiCompletedEventHandler b2b_twrzamiennikiCompleted;
        
        /// <remarks/>
        public event testCompletedEventHandler testCompleted;
        
        /// <remarks/>
        public event b2b_verifyUserCompletedEventHandler b2b_verifyUserCompleted;
        
        /// <remarks/>
        public event b2b_setNewUserPasswordCompletedEventHandler b2b_setNewUserPasswordCompleted;
        
        /// <remarks/>
        public event b2b_NumerWebCompletedEventHandler b2b_NumerWebCompleted;
        
        /// <remarks/>
        public event b2b_cdloginlogoutCompletedEventHandler b2b_cdloginlogoutCompleted;
        
        /// <remarks/>
        public event b2b_nowyDokumentZamCompletedEventHandler b2b_nowyDokumentZamCompleted;
        
        /// <remarks/>
        public event b2b_nowyDokumentZamHanCompletedEventHandler b2b_nowyDokumentZamHanCompleted;
        
        /// <remarks/>
        public event b2b_adresykontrahentowCompletedEventHandler b2b_adresykontrahentowCompleted;
        
        /// <remarks/>
        public event b2b_AdresyKontrahentaCompletedEventHandler b2b_AdresyKontrahentaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/b2b_towary", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string b2b_towary() {
            object[] results = this.Invoke("b2b_towary", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void b2b_towaryAsync() {
            this.b2b_towaryAsync(null);
        }
        
        /// <remarks/>
        public void b2b_towaryAsync(object userState) {
            if ((this.b2b_towaryOperationCompleted == null)) {
                this.b2b_towaryOperationCompleted = new System.Threading.SendOrPostCallback(this.Onb2b_towaryOperationCompleted);
            }
            this.InvokeAsync("b2b_towary", new object[0], this.b2b_towaryOperationCompleted, userState);
        }
        
        private void Onb2b_towaryOperationCompleted(object arg) {
            if ((this.b2b_towaryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.b2b_towaryCompleted(this, new b2b_towaryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/b2b_grupy", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string b2b_grupy() {
            object[] results = this.Invoke("b2b_grupy", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void b2b_grupyAsync() {
            this.b2b_grupyAsync(null);
        }
        
        /// <remarks/>
        public void b2b_grupyAsync(object userState) {
            if ((this.b2b_grupyOperationCompleted == null)) {
                this.b2b_grupyOperationCompleted = new System.Threading.SendOrPostCallback(this.Onb2b_grupyOperationCompleted);
            }
            this.InvokeAsync("b2b_grupy", new object[0], this.b2b_grupyOperationCompleted, userState);
        }
        
        private void Onb2b_grupyOperationCompleted(object arg) {
            if ((this.b2b_grupyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.b2b_grupyCompleted(this, new b2b_grupyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/b2b_CenySpecjalne", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string b2b_CenySpecjalne(int kntId) {
            object[] results = this.Invoke("b2b_CenySpecjalne", new object[] {
                        kntId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void b2b_CenySpecjalneAsync(int kntId) {
            this.b2b_CenySpecjalneAsync(kntId, null);
        }
        
        /// <remarks/>
        public void b2b_CenySpecjalneAsync(int kntId, object userState) {
            if ((this.b2b_CenySpecjalneOperationCompleted == null)) {
                this.b2b_CenySpecjalneOperationCompleted = new System.Threading.SendOrPostCallback(this.Onb2b_CenySpecjalneOperationCompleted);
            }
            this.InvokeAsync("b2b_CenySpecjalne", new object[] {
                        kntId}, this.b2b_CenySpecjalneOperationCompleted, userState);
        }
        
        private void Onb2b_CenySpecjalneOperationCompleted(object arg) {
            if ((this.b2b_CenySpecjalneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.b2b_CenySpecjalneCompleted(this, new b2b_CenySpecjalneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/b2b_kontrahenci", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string b2b_kontrahenci() {
            object[] results = this.Invoke("b2b_kontrahenci", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void b2b_kontrahenciAsync() {
            this.b2b_kontrahenciAsync(null);
        }
        
        /// <remarks/>
        public void b2b_kontrahenciAsync(object userState) {
            if ((this.b2b_kontrahenciOperationCompleted == null)) {
                this.b2b_kontrahenciOperationCompleted = new System.Threading.SendOrPostCallback(this.Onb2b_kontrahenciOperationCompleted);
            }
            this.InvokeAsync("b2b_kontrahenci", new object[0], this.b2b_kontrahenciOperationCompleted, userState);
        }
        
        private void Onb2b_kontrahenciOperationCompleted(object arg) {
            if ((this.b2b_kontrahenciCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.b2b_kontrahenciCompleted(this, new b2b_kontrahenciCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/b2b_danebinarne", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string b2b_danebinarne() {
            object[] results = this.Invoke("b2b_danebinarne", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void b2b_danebinarneAsync() {
            this.b2b_danebinarneAsync(null);
        }
        
        /// <remarks/>
        public void b2b_danebinarneAsync(object userState) {
            if ((this.b2b_danebinarneOperationCompleted == null)) {
                this.b2b_danebinarneOperationCompleted = new System.Threading.SendOrPostCallback(this.Onb2b_danebinarneOperationCompleted);
            }
            this.InvokeAsync("b2b_danebinarne", new object[0], this.b2b_danebinarneOperationCompleted, userState);
        }
        
        private void Onb2b_danebinarneOperationCompleted(object arg) {
            if ((this.b2b_danebinarneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.b2b_danebinarneCompleted(this, new b2b_danebinarneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/b2b_operatorzy", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string b2b_operatorzy() {
            object[] results = this.Invoke("b2b_operatorzy", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void b2b_operatorzyAsync() {
            this.b2b_operatorzyAsync(null);
        }
        
        /// <remarks/>
        public void b2b_operatorzyAsync(object userState) {
            if ((this.b2b_operatorzyOperationCompleted == null)) {
                this.b2b_operatorzyOperationCompleted = new System.Threading.SendOrPostCallback(this.Onb2b_operatorzyOperationCompleted);
            }
            this.InvokeAsync("b2b_operatorzy", new object[0], this.b2b_operatorzyOperationCompleted, userState);
        }
        
        private void Onb2b_operatorzyOperationCompleted(object arg) {
            if ((this.b2b_operatorzyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.b2b_operatorzyCompleted(this, new b2b_operatorzyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/b2b_dystrybutorzy", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string b2b_dystrybutorzy() {
            object[] results = this.Invoke("b2b_dystrybutorzy", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void b2b_dystrybutorzyAsync() {
            this.b2b_dystrybutorzyAsync(null);
        }
        
        /// <remarks/>
        public void b2b_dystrybutorzyAsync(object userState) {
            if ((this.b2b_dystrybutorzyOperationCompleted == null)) {
                this.b2b_dystrybutorzyOperationCompleted = new System.Threading.SendOrPostCallback(this.Onb2b_dystrybutorzyOperationCompleted);
            }
            this.InvokeAsync("b2b_dystrybutorzy", new object[0], this.b2b_dystrybutorzyOperationCompleted, userState);
        }
        
        private void Onb2b_dystrybutorzyOperationCompleted(object arg) {
            if ((this.b2b_dystrybutorzyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.b2b_dystrybutorzyCompleted(this, new b2b_dystrybutorzyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/b2b_cenyklientow", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string b2b_cenyklientow(int kntId) {
            object[] results = this.Invoke("b2b_cenyklientow", new object[] {
                        kntId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void b2b_cenyklientowAsync(int kntId) {
            this.b2b_cenyklientowAsync(kntId, null);
        }
        
        /// <remarks/>
        public void b2b_cenyklientowAsync(int kntId, object userState) {
            if ((this.b2b_cenyklientowOperationCompleted == null)) {
                this.b2b_cenyklientowOperationCompleted = new System.Threading.SendOrPostCallback(this.Onb2b_cenyklientowOperationCompleted);
            }
            this.InvokeAsync("b2b_cenyklientow", new object[] {
                        kntId}, this.b2b_cenyklientowOperationCompleted, userState);
        }
        
        private void Onb2b_cenyklientowOperationCompleted(object arg) {
            if ((this.b2b_cenyklientowCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.b2b_cenyklientowCompleted(this, new b2b_cenyklientowCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/b2b_cechy", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string b2b_cechy(int twrId) {
            object[] results = this.Invoke("b2b_cechy", new object[] {
                        twrId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void b2b_cechyAsync(int twrId) {
            this.b2b_cechyAsync(twrId, null);
        }
        
        /// <remarks/>
        public void b2b_cechyAsync(int twrId, object userState) {
            if ((this.b2b_cechyOperationCompleted == null)) {
                this.b2b_cechyOperationCompleted = new System.Threading.SendOrPostCallback(this.Onb2b_cechyOperationCompleted);
            }
            this.InvokeAsync("b2b_cechy", new object[] {
                        twrId}, this.b2b_cechyOperationCompleted, userState);
        }
        
        private void Onb2b_cechyOperationCompleted(object arg) {
            if ((this.b2b_cechyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.b2b_cechyCompleted(this, new b2b_cechyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/b2b_stany", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string b2b_stany(int Id) {
            object[] results = this.Invoke("b2b_stany", new object[] {
                        Id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void b2b_stanyAsync(int Id) {
            this.b2b_stanyAsync(Id, null);
        }
        
        /// <remarks/>
        public void b2b_stanyAsync(int Id, object userState) {
            if ((this.b2b_stanyOperationCompleted == null)) {
                this.b2b_stanyOperationCompleted = new System.Threading.SendOrPostCallback(this.Onb2b_stanyOperationCompleted);
            }
            this.InvokeAsync("b2b_stany", new object[] {
                        Id}, this.b2b_stanyOperationCompleted, userState);
        }
        
        private void Onb2b_stanyOperationCompleted(object arg) {
            if ((this.b2b_stanyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.b2b_stanyCompleted(this, new b2b_stanyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/b2b_zamnag", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string b2b_zamnag(int gidnumer) {
            object[] results = this.Invoke("b2b_zamnag", new object[] {
                        gidnumer});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void b2b_zamnagAsync(int gidnumer) {
            this.b2b_zamnagAsync(gidnumer, null);
        }
        
        /// <remarks/>
        public void b2b_zamnagAsync(int gidnumer, object userState) {
            if ((this.b2b_zamnagOperationCompleted == null)) {
                this.b2b_zamnagOperationCompleted = new System.Threading.SendOrPostCallback(this.Onb2b_zamnagOperationCompleted);
            }
            this.InvokeAsync("b2b_zamnag", new object[] {
                        gidnumer}, this.b2b_zamnagOperationCompleted, userState);
        }
        
        private void Onb2b_zamnagOperationCompleted(object arg) {
            if ((this.b2b_zamnagCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.b2b_zamnagCompleted(this, new b2b_zamnagCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/b2b_zamelem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string b2b_zamelem(int gidnumer, int kndnumer) {
            object[] results = this.Invoke("b2b_zamelem", new object[] {
                        gidnumer,
                        kndnumer});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void b2b_zamelemAsync(int gidnumer, int kndnumer) {
            this.b2b_zamelemAsync(gidnumer, kndnumer, null);
        }
        
        /// <remarks/>
        public void b2b_zamelemAsync(int gidnumer, int kndnumer, object userState) {
            if ((this.b2b_zamelemOperationCompleted == null)) {
                this.b2b_zamelemOperationCompleted = new System.Threading.SendOrPostCallback(this.Onb2b_zamelemOperationCompleted);
            }
            this.InvokeAsync("b2b_zamelem", new object[] {
                        gidnumer,
                        kndnumer}, this.b2b_zamelemOperationCompleted, userState);
        }
        
        private void Onb2b_zamelemOperationCompleted(object arg) {
            if ((this.b2b_zamelemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.b2b_zamelemCompleted(this, new b2b_zamelemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/b2b_nowyAdres", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string b2b_nowyAdres(string xml) {
            object[] results = this.Invoke("b2b_nowyAdres", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void b2b_nowyAdresAsync(string xml) {
            this.b2b_nowyAdresAsync(xml, null);
        }
        
        /// <remarks/>
        public void b2b_nowyAdresAsync(string xml, object userState) {
            if ((this.b2b_nowyAdresOperationCompleted == null)) {
                this.b2b_nowyAdresOperationCompleted = new System.Threading.SendOrPostCallback(this.Onb2b_nowyAdresOperationCompleted);
            }
            this.InvokeAsync("b2b_nowyAdres", new object[] {
                        xml}, this.b2b_nowyAdresOperationCompleted, userState);
        }
        
        private void Onb2b_nowyAdresOperationCompleted(object arg) {
            if ((this.b2b_nowyAdresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.b2b_nowyAdresCompleted(this, new b2b_nowyAdresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/b2b_traelem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string b2b_traelem(int trnnumer, int kndnumer) {
            object[] results = this.Invoke("b2b_traelem", new object[] {
                        trnnumer,
                        kndnumer});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void b2b_traelemAsync(int trnnumer, int kndnumer) {
            this.b2b_traelemAsync(trnnumer, kndnumer, null);
        }
        
        /// <remarks/>
        public void b2b_traelemAsync(int trnnumer, int kndnumer, object userState) {
            if ((this.b2b_traelemOperationCompleted == null)) {
                this.b2b_traelemOperationCompleted = new System.Threading.SendOrPostCallback(this.Onb2b_traelemOperationCompleted);
            }
            this.InvokeAsync("b2b_traelem", new object[] {
                        trnnumer,
                        kndnumer}, this.b2b_traelemOperationCompleted, userState);
        }
        
        private void Onb2b_traelemOperationCompleted(object arg) {
            if ((this.b2b_traelemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.b2b_traelemCompleted(this, new b2b_traelemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/b2b_tranag", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string b2b_tranag(int gidnumer) {
            object[] results = this.Invoke("b2b_tranag", new object[] {
                        gidnumer});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void b2b_tranagAsync(int gidnumer) {
            this.b2b_tranagAsync(gidnumer, null);
        }
        
        /// <remarks/>
        public void b2b_tranagAsync(int gidnumer, object userState) {
            if ((this.b2b_tranagOperationCompleted == null)) {
                this.b2b_tranagOperationCompleted = new System.Threading.SendOrPostCallback(this.Onb2b_tranagOperationCompleted);
            }
            this.InvokeAsync("b2b_tranag", new object[] {
                        gidnumer}, this.b2b_tranagOperationCompleted, userState);
        }
        
        private void Onb2b_tranagOperationCompleted(object arg) {
            if ((this.b2b_tranagCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.b2b_tranagCompleted(this, new b2b_tranagCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/b2b_ceny", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string b2b_ceny(int Id) {
            object[] results = this.Invoke("b2b_ceny", new object[] {
                        Id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void b2b_cenyAsync(int Id) {
            this.b2b_cenyAsync(Id, null);
        }
        
        /// <remarks/>
        public void b2b_cenyAsync(int Id, object userState) {
            if ((this.b2b_cenyOperationCompleted == null)) {
                this.b2b_cenyOperationCompleted = new System.Threading.SendOrPostCallback(this.Onb2b_cenyOperationCompleted);
            }
            this.InvokeAsync("b2b_ceny", new object[] {
                        Id}, this.b2b_cenyOperationCompleted, userState);
        }
        
        private void Onb2b_cenyOperationCompleted(object arg) {
            if ((this.b2b_cenyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.b2b_cenyCompleted(this, new b2b_cenyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/b2b_twrzamienniki", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string b2b_twrzamienniki() {
            object[] results = this.Invoke("b2b_twrzamienniki", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void b2b_twrzamiennikiAsync() {
            this.b2b_twrzamiennikiAsync(null);
        }
        
        /// <remarks/>
        public void b2b_twrzamiennikiAsync(object userState) {
            if ((this.b2b_twrzamiennikiOperationCompleted == null)) {
                this.b2b_twrzamiennikiOperationCompleted = new System.Threading.SendOrPostCallback(this.Onb2b_twrzamiennikiOperationCompleted);
            }
            this.InvokeAsync("b2b_twrzamienniki", new object[0], this.b2b_twrzamiennikiOperationCompleted, userState);
        }
        
        private void Onb2b_twrzamiennikiOperationCompleted(object arg) {
            if ((this.b2b_twrzamiennikiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.b2b_twrzamiennikiCompleted(this, new b2b_twrzamiennikiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/test", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string test() {
            object[] results = this.Invoke("test", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void testAsync() {
            this.testAsync(null);
        }
        
        /// <remarks/>
        public void testAsync(object userState) {
            if ((this.testOperationCompleted == null)) {
                this.testOperationCompleted = new System.Threading.SendOrPostCallback(this.OntestOperationCompleted);
            }
            this.InvokeAsync("test", new object[0], this.testOperationCompleted, userState);
        }
        
        private void OntestOperationCompleted(object arg) {
            if ((this.testCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.testCompleted(this, new testCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/b2b_verifyUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string b2b_verifyUser(string name, string password) {
            object[] results = this.Invoke("b2b_verifyUser", new object[] {
                        name,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void b2b_verifyUserAsync(string name, string password) {
            this.b2b_verifyUserAsync(name, password, null);
        }
        
        /// <remarks/>
        public void b2b_verifyUserAsync(string name, string password, object userState) {
            if ((this.b2b_verifyUserOperationCompleted == null)) {
                this.b2b_verifyUserOperationCompleted = new System.Threading.SendOrPostCallback(this.Onb2b_verifyUserOperationCompleted);
            }
            this.InvokeAsync("b2b_verifyUser", new object[] {
                        name,
                        password}, this.b2b_verifyUserOperationCompleted, userState);
        }
        
        private void Onb2b_verifyUserOperationCompleted(object arg) {
            if ((this.b2b_verifyUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.b2b_verifyUserCompleted(this, new b2b_verifyUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/b2b_setNewUserPassword", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string b2b_setNewUserPassword(string name) {
            object[] results = this.Invoke("b2b_setNewUserPassword", new object[] {
                        name});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void b2b_setNewUserPasswordAsync(string name) {
            this.b2b_setNewUserPasswordAsync(name, null);
        }
        
        /// <remarks/>
        public void b2b_setNewUserPasswordAsync(string name, object userState) {
            if ((this.b2b_setNewUserPasswordOperationCompleted == null)) {
                this.b2b_setNewUserPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.Onb2b_setNewUserPasswordOperationCompleted);
            }
            this.InvokeAsync("b2b_setNewUserPassword", new object[] {
                        name}, this.b2b_setNewUserPasswordOperationCompleted, userState);
        }
        
        private void Onb2b_setNewUserPasswordOperationCompleted(object arg) {
            if ((this.b2b_setNewUserPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.b2b_setNewUserPasswordCompleted(this, new b2b_setNewUserPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/b2b_NumerWeb", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string b2b_NumerWeb(int kntid, string numer) {
            object[] results = this.Invoke("b2b_NumerWeb", new object[] {
                        kntid,
                        numer});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void b2b_NumerWebAsync(int kntid, string numer) {
            this.b2b_NumerWebAsync(kntid, numer, null);
        }
        
        /// <remarks/>
        public void b2b_NumerWebAsync(int kntid, string numer, object userState) {
            if ((this.b2b_NumerWebOperationCompleted == null)) {
                this.b2b_NumerWebOperationCompleted = new System.Threading.SendOrPostCallback(this.Onb2b_NumerWebOperationCompleted);
            }
            this.InvokeAsync("b2b_NumerWeb", new object[] {
                        kntid,
                        numer}, this.b2b_NumerWebOperationCompleted, userState);
        }
        
        private void Onb2b_NumerWebOperationCompleted(object arg) {
            if ((this.b2b_NumerWebCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.b2b_NumerWebCompleted(this, new b2b_NumerWebCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/b2b_cdloginlogout", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string b2b_cdloginlogout() {
            object[] results = this.Invoke("b2b_cdloginlogout", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void b2b_cdloginlogoutAsync() {
            this.b2b_cdloginlogoutAsync(null);
        }
        
        /// <remarks/>
        public void b2b_cdloginlogoutAsync(object userState) {
            if ((this.b2b_cdloginlogoutOperationCompleted == null)) {
                this.b2b_cdloginlogoutOperationCompleted = new System.Threading.SendOrPostCallback(this.Onb2b_cdloginlogoutOperationCompleted);
            }
            this.InvokeAsync("b2b_cdloginlogout", new object[0], this.b2b_cdloginlogoutOperationCompleted, userState);
        }
        
        private void Onb2b_cdloginlogoutOperationCompleted(object arg) {
            if ((this.b2b_cdloginlogoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.b2b_cdloginlogoutCompleted(this, new b2b_cdloginlogoutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/b2b_nowyDokumentZam", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string b2b_nowyDokumentZam(string xml) {
            object[] results = this.Invoke("b2b_nowyDokumentZam", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void b2b_nowyDokumentZamAsync(string xml) {
            this.b2b_nowyDokumentZamAsync(xml, null);
        }
        
        /// <remarks/>
        public void b2b_nowyDokumentZamAsync(string xml, object userState) {
            if ((this.b2b_nowyDokumentZamOperationCompleted == null)) {
                this.b2b_nowyDokumentZamOperationCompleted = new System.Threading.SendOrPostCallback(this.Onb2b_nowyDokumentZamOperationCompleted);
            }
            this.InvokeAsync("b2b_nowyDokumentZam", new object[] {
                        xml}, this.b2b_nowyDokumentZamOperationCompleted, userState);
        }
        
        private void Onb2b_nowyDokumentZamOperationCompleted(object arg) {
            if ((this.b2b_nowyDokumentZamCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.b2b_nowyDokumentZamCompleted(this, new b2b_nowyDokumentZamCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/b2b_nowyDokumentZamHan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string b2b_nowyDokumentZamHan(string zamXml, string hanXml, string pathToSet) {
            object[] results = this.Invoke("b2b_nowyDokumentZamHan", new object[] {
                        zamXml,
                        hanXml,
                        pathToSet});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void b2b_nowyDokumentZamHanAsync(string zamXml, string hanXml, string pathToSet) {
            this.b2b_nowyDokumentZamHanAsync(zamXml, hanXml, pathToSet, null);
        }
        
        /// <remarks/>
        public void b2b_nowyDokumentZamHanAsync(string zamXml, string hanXml, string pathToSet, object userState) {
            if ((this.b2b_nowyDokumentZamHanOperationCompleted == null)) {
                this.b2b_nowyDokumentZamHanOperationCompleted = new System.Threading.SendOrPostCallback(this.Onb2b_nowyDokumentZamHanOperationCompleted);
            }
            this.InvokeAsync("b2b_nowyDokumentZamHan", new object[] {
                        zamXml,
                        hanXml,
                        pathToSet}, this.b2b_nowyDokumentZamHanOperationCompleted, userState);
        }
        
        private void Onb2b_nowyDokumentZamHanOperationCompleted(object arg) {
            if ((this.b2b_nowyDokumentZamHanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.b2b_nowyDokumentZamHanCompleted(this, new b2b_nowyDokumentZamHanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/b2b_adresykontrahentow", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string b2b_adresykontrahentow() {
            object[] results = this.Invoke("b2b_adresykontrahentow", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void b2b_adresykontrahentowAsync() {
            this.b2b_adresykontrahentowAsync(null);
        }
        
        /// <remarks/>
        public void b2b_adresykontrahentowAsync(object userState) {
            if ((this.b2b_adresykontrahentowOperationCompleted == null)) {
                this.b2b_adresykontrahentowOperationCompleted = new System.Threading.SendOrPostCallback(this.Onb2b_adresykontrahentowOperationCompleted);
            }
            this.InvokeAsync("b2b_adresykontrahentow", new object[0], this.b2b_adresykontrahentowOperationCompleted, userState);
        }
        
        private void Onb2b_adresykontrahentowOperationCompleted(object arg) {
            if ((this.b2b_adresykontrahentowCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.b2b_adresykontrahentowCompleted(this, new b2b_adresykontrahentowCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/b2b_AdresyKontrahenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string b2b_AdresyKontrahenta(int kntnumer) {
            object[] results = this.Invoke("b2b_AdresyKontrahenta", new object[] {
                        kntnumer});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void b2b_AdresyKontrahentaAsync(int kntnumer) {
            this.b2b_AdresyKontrahentaAsync(kntnumer, null);
        }
        
        /// <remarks/>
        public void b2b_AdresyKontrahentaAsync(int kntnumer, object userState) {
            if ((this.b2b_AdresyKontrahentaOperationCompleted == null)) {
                this.b2b_AdresyKontrahentaOperationCompleted = new System.Threading.SendOrPostCallback(this.Onb2b_AdresyKontrahentaOperationCompleted);
            }
            this.InvokeAsync("b2b_AdresyKontrahenta", new object[] {
                        kntnumer}, this.b2b_AdresyKontrahentaOperationCompleted, userState);
        }
        
        private void Onb2b_AdresyKontrahentaOperationCompleted(object arg) {
            if ((this.b2b_AdresyKontrahentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.b2b_AdresyKontrahentaCompleted(this, new b2b_AdresyKontrahentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void b2b_towaryCompletedEventHandler(object sender, b2b_towaryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class b2b_towaryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal b2b_towaryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void b2b_grupyCompletedEventHandler(object sender, b2b_grupyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class b2b_grupyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal b2b_grupyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void b2b_CenySpecjalneCompletedEventHandler(object sender, b2b_CenySpecjalneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class b2b_CenySpecjalneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal b2b_CenySpecjalneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void b2b_kontrahenciCompletedEventHandler(object sender, b2b_kontrahenciCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class b2b_kontrahenciCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal b2b_kontrahenciCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void b2b_danebinarneCompletedEventHandler(object sender, b2b_danebinarneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class b2b_danebinarneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal b2b_danebinarneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void b2b_operatorzyCompletedEventHandler(object sender, b2b_operatorzyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class b2b_operatorzyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal b2b_operatorzyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void b2b_dystrybutorzyCompletedEventHandler(object sender, b2b_dystrybutorzyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class b2b_dystrybutorzyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal b2b_dystrybutorzyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void b2b_cenyklientowCompletedEventHandler(object sender, b2b_cenyklientowCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class b2b_cenyklientowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal b2b_cenyklientowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void b2b_cechyCompletedEventHandler(object sender, b2b_cechyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class b2b_cechyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal b2b_cechyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void b2b_stanyCompletedEventHandler(object sender, b2b_stanyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class b2b_stanyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal b2b_stanyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void b2b_zamnagCompletedEventHandler(object sender, b2b_zamnagCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class b2b_zamnagCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal b2b_zamnagCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void b2b_zamelemCompletedEventHandler(object sender, b2b_zamelemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class b2b_zamelemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal b2b_zamelemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void b2b_nowyAdresCompletedEventHandler(object sender, b2b_nowyAdresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class b2b_nowyAdresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal b2b_nowyAdresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void b2b_traelemCompletedEventHandler(object sender, b2b_traelemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class b2b_traelemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal b2b_traelemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void b2b_tranagCompletedEventHandler(object sender, b2b_tranagCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class b2b_tranagCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal b2b_tranagCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void b2b_cenyCompletedEventHandler(object sender, b2b_cenyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class b2b_cenyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal b2b_cenyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void b2b_twrzamiennikiCompletedEventHandler(object sender, b2b_twrzamiennikiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class b2b_twrzamiennikiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal b2b_twrzamiennikiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void testCompletedEventHandler(object sender, testCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class testCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal testCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void b2b_verifyUserCompletedEventHandler(object sender, b2b_verifyUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class b2b_verifyUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal b2b_verifyUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void b2b_setNewUserPasswordCompletedEventHandler(object sender, b2b_setNewUserPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class b2b_setNewUserPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal b2b_setNewUserPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void b2b_NumerWebCompletedEventHandler(object sender, b2b_NumerWebCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class b2b_NumerWebCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal b2b_NumerWebCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void b2b_cdloginlogoutCompletedEventHandler(object sender, b2b_cdloginlogoutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class b2b_cdloginlogoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal b2b_cdloginlogoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void b2b_nowyDokumentZamCompletedEventHandler(object sender, b2b_nowyDokumentZamCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class b2b_nowyDokumentZamCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal b2b_nowyDokumentZamCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void b2b_nowyDokumentZamHanCompletedEventHandler(object sender, b2b_nowyDokumentZamHanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class b2b_nowyDokumentZamHanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal b2b_nowyDokumentZamHanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void b2b_adresykontrahentowCompletedEventHandler(object sender, b2b_adresykontrahentowCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class b2b_adresykontrahentowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal b2b_adresykontrahentowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void b2b_AdresyKontrahentaCompletedEventHandler(object sender, b2b_AdresyKontrahentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class b2b_AdresyKontrahentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal b2b_AdresyKontrahentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591