//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BemkoStanyMagazynowe.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"select twr_kod Symbol, convert(varchar(10),getdate(), 121) Data,

case when CDN.bmp_DokSumaStanowTowaru(Twr_GIDTyp,Twr_GIDFirma,Twr_GIDNumer,Twr_Typ,1,1,1,Twr_GIDFirma,12,0,0,0, DATEDIFF(d,'1800-12-28T00:00:00',getdate()), 0,3, 0,0,0,0,0,0,0,0) < 0 then 0

else CDN.bmp_DokSumaStanowTowaru(Twr_GIDTyp,Twr_GIDFirma,Twr_GIDNumer,Twr_Typ,1,1,1,Twr_GIDFirma,12,0,0,0, DATEDIFF(d,'1800-12-28T00:00:00',getdate()), 0,3, 0,0,0,0,0,0,0,0) end Stan

,Twr_JM Jm

from cdn.TwrKarty

where Twr_Typ in (1,2)

and Twr_Archiwalny=0")]
        public string stanyMagazynoweQuery {
            get {
                return ((string)(this["stanyMagazynoweQuery"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Machine")]
        public string loginContext {
            get {
                return ((string)(this["loginContext"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0.0")]
        public string wersja {
            get {
                return ((string)(this["wersja"]));
            }
        }
    }
}
