//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BemkoStanyMagazynoweTest.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.BemkoStanyMagazynoweSoap")]
    public interface BemkoStanyMagazynoweSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pobierzStanMagazynowyProducenta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BemkoStanyMagazynoweTest.ServiceReference1.odpowiedz pobierzStanMagazynowyProducenta(BemkoStanyMagazynoweTest.ServiceReference1.pytanie pytanie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pobierzStanMagazynowyProducenta", ReplyAction="*")]
        System.Threading.Tasks.Task<BemkoStanyMagazynoweTest.ServiceReference1.odpowiedz> pobierzStanMagazynowyProducentaAsync(BemkoStanyMagazynoweTest.ServiceReference1.pytanie pytanie);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://megacennik.eu/pobierzStanMagazynowyProducenta/")]
    public partial class pytanie : object, System.ComponentModel.INotifyPropertyChanged {
        
        private dokumentTyp dokumentField;
        
        private kontoTyp kontoField;
        
        private towarPytanieTyp[] towaryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public dokumentTyp dokument {
            get {
                return this.dokumentField;
            }
            set {
                this.dokumentField = value;
                this.RaisePropertyChanged("dokument");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public kontoTyp konto {
            get {
                return this.kontoField;
            }
            set {
                this.kontoField = value;
                this.RaisePropertyChanged("konto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("towar", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public towarPytanieTyp[] towary {
            get {
                return this.towaryField;
            }
            set {
                this.towaryField = value;
                this.RaisePropertyChanged("towary");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://megacennik.eu/pobierzStanMagazynowyProducenta/")]
    public partial class dokumentTyp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string wersjaField;
        
        private System.DateTime znacznikField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string wersja {
            get {
                return this.wersjaField;
            }
            set {
                this.wersjaField = value;
                this.RaisePropertyChanged("wersja");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime znacznik {
            get {
                return this.znacznikField;
            }
            set {
                this.znacznikField = value;
                this.RaisePropertyChanged("znacznik");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://megacennik.eu/pobierzStanMagazynowyProducenta/")]
    public partial class towarOdpowiedzTyp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string symbolField;
        
        private double iloscField;
        
        private bool iloscFieldSpecified;
        
        private System.DateTime dataField;
        
        private bool dataFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
                this.RaisePropertyChanged("symbol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double ilosc {
            get {
                return this.iloscField;
            }
            set {
                this.iloscField = value;
                this.RaisePropertyChanged("ilosc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool iloscSpecified {
            get {
                return this.iloscFieldSpecified;
            }
            set {
                this.iloscFieldSpecified = value;
                this.RaisePropertyChanged("iloscSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataSpecified {
            get {
                return this.dataFieldSpecified;
            }
            set {
                this.dataFieldSpecified = value;
                this.RaisePropertyChanged("dataSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://megacennik.eu/pobierzStanMagazynowyProducenta/")]
    public partial class odpowiedz : object, System.ComponentModel.INotifyPropertyChanged {
        
        private towarOdpowiedzTyp[] towaryField;
        
        private string wersjaField;
        
        private System.DateTime znacznikField;
        
        private bool znacznikFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("towar", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public towarOdpowiedzTyp[] towary {
            get {
                return this.towaryField;
            }
            set {
                this.towaryField = value;
                this.RaisePropertyChanged("towary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string wersja {
            get {
                return this.wersjaField;
            }
            set {
                this.wersjaField = value;
                this.RaisePropertyChanged("wersja");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime znacznik {
            get {
                return this.znacznikField;
            }
            set {
                this.znacznikField = value;
                this.RaisePropertyChanged("znacznik");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool znacznikSpecified {
            get {
                return this.znacznikFieldSpecified;
            }
            set {
                this.znacznikFieldSpecified = value;
                this.RaisePropertyChanged("znacznikSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://megacennik.eu/pobierzStanMagazynowyProducenta/")]
    public partial class towarPytanieTyp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string symbolField;
        
        private double iloscField;
        
        private bool iloscFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
                this.RaisePropertyChanged("symbol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double ilosc {
            get {
                return this.iloscField;
            }
            set {
                this.iloscField = value;
                this.RaisePropertyChanged("ilosc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool iloscSpecified {
            get {
                return this.iloscFieldSpecified;
            }
            set {
                this.iloscFieldSpecified = value;
                this.RaisePropertyChanged("iloscSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://megacennik.eu/pobierzStanMagazynowyProducenta/")]
    public partial class kontoTyp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string loginField;
        
        private string hasloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string haslo {
            get {
                return this.hasloField;
            }
            set {
                this.hasloField = value;
                this.RaisePropertyChanged("haslo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BemkoStanyMagazynoweSoapChannel : BemkoStanyMagazynoweTest.ServiceReference1.BemkoStanyMagazynoweSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BemkoStanyMagazynoweSoapClient : System.ServiceModel.ClientBase<BemkoStanyMagazynoweTest.ServiceReference1.BemkoStanyMagazynoweSoap>, BemkoStanyMagazynoweTest.ServiceReference1.BemkoStanyMagazynoweSoap {
        
        public BemkoStanyMagazynoweSoapClient() {
        }
        
        public BemkoStanyMagazynoweSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BemkoStanyMagazynoweSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BemkoStanyMagazynoweSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BemkoStanyMagazynoweSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BemkoStanyMagazynoweTest.ServiceReference1.odpowiedz pobierzStanMagazynowyProducenta(BemkoStanyMagazynoweTest.ServiceReference1.pytanie pytanie) {
            return base.Channel.pobierzStanMagazynowyProducenta(pytanie);
        }
        
        public System.Threading.Tasks.Task<BemkoStanyMagazynoweTest.ServiceReference1.odpowiedz> pobierzStanMagazynowyProducentaAsync(BemkoStanyMagazynoweTest.ServiceReference1.pytanie pytanie) {
            return base.Channel.pobierzStanMagazynowyProducentaAsync(pytanie);
        }
    }
}
